name: Build Github Package

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    if: github.repository == 'decooio/ipfs-w3auth-pinning-service'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DECOO_PAT }}

      - name: Login to TCR private docker registry
        uses: docker/login-action@v1
        with:
          registry: decoo-registry.tencentcloudcr.com
          username: ${{ secrets.TCR_USER }}
          password: ${{ secrets.TCR_PASSWD }}


      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/decooio/ipfs-w3auth-pinning-service:latest, decoo-registry.tencentcloudcr.com/decooio/ipfs-w3auth-pinning-service:latest
