name: Build ipfs w3auth pinning service

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    if: github.repository == 'crustio/ipfs-w3auth-pinning-service'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
